### PR TITLE
Remove call to time to fix pip install

### PR DESCRIPTION
**Pull request by yrp604**
On recent Ubuntu, 'time' is provided either by the 'time' package, or as a bash builtin. It's not present in sh, or installed by default. This causes 'pip install keystone-engine' to fail.

So, one of the following needs to happen:
-'time' package is added to the pre-reqs
-switch this script to bash
-remove the 'time' call around make

I've axed the call to 'time', but really whatever you think is best.

### CODE REVIEW

**Comment by aquynh** [comment]
Which distro are you using?

**Comment by yrp604** [comment]
xenial on armv7l

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
i just pushed out a new PyPi package `keystone-engine-0.9.1-3` with this change. let me know if you still have issues, thanks.

**Comment by yrp604** [comment]
Ok, this fixes my issue, but I also might have been an idiot and removed the time utility on accident at some point in the past :|

**Pull request merged**
