### PR TITLE
added regression test for "jmp 0x33, 08"

### PR DESCRIPTION
**Pull request by mrexodia**
for issue #214

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
can you fix this test by adding the expected output?

**Comment by mrexodia** [comment]
I don't have the expected output 👍

**Comment by aquynh** [comment]
meaning you are happy with any output?

we need the right output to avoid future regression here.

**Comment by mrexodia** [comment]
I mean it's an invalid instruction so there shouldn't really be an output
right?

**Comment by aquynh** [comment]
i think we care more about "jmp 0x30:8", which is also incorrectly handled
now.

and we need the output of this instruction, which can also be put in the
same testcase.

**Comment by mrexodia** [comment]
Well in that case I cannot help, I don't have a 16 bit assembler at my
disposal.

**Comment by aquynh** [comment]
Intel Xed does not support 16bit?

**Comment by mrexodia** [comment]
I'm currently in Paris in some train station without xed on my phone 👍

**Comment by aquynh** [comment]
ok i changed that to reflect the expected output. if XED gives out the different output, please report here.

**Pull request merged**
