### PR TITLE
bindings: build keystone binary on Rust bindings

### PR DESCRIPTION
**Pull request by gunyarakun**
Current Rust bindings for keystone works well, but I've found some points to be possibly improved.

- [OPT_SYM_RESOLVER](https://github.com/keystone-engine/keystone/blob/master/bindings/rust/src/keystone_const.rs#L91) should be OptionType, but OptionValue.
- Rust bindings of `capstone` and `unicorn` contains the target libraries themselves. That is easy to use and doesn't require users to take care of library version difference.
- [bindings/rust/src/enums.rs is not loaded](https://github.com/keystone-engine/keystone/blob/b2996ada87a2def0d67b69a2c3338785c5b03d98/bindings/rust/src/lib.rs#L26), but the author's original intent should be to load the file so that function arguments are well-typed.
    - [A sample code written in README.md was not able to be compiled and I fixed it](https://github.com/keystone-engine/keystone/commit/db87c0bcc233a6e88ef09f8aec276e28b6b38d4b#diff-fb6b7fb7e3d7e43d6ec1338001ee5600). The original sample code seems to have been written in the environment loading `enums.rs`.

To improve these things, this pull request does the following.

- Modify `bindings/const_generator.py` to generate proper constants.
- Split into 2 crates, `keystone` and `keystone-sys` like capstone and unicorn rust bindings.
    - `keystone-sys` contains keystone itself and is built on installation of the crate.
    - `keystone-sys` can link with keystone installed into the system. In this case, included keystone isn't compiled.

After applying this pull request, minor version of bindings should be updated because of some incompatibilities of constants like following.

Former:

```rust
let engine = Keystone::new(Arch::X86, MODE_32).unwrap();
engine.option(OptionType::SYNTAX, keystone::OPT_SYNTAX_NASM);
```

After applying this patch:

```rust
let engine = Keystone::new(Arch::X86, Mode::MODE_32).unwrap();
engine.option(OptionType::SYNTAX, OptionValue::SYNTAX_NASM);
```

### CODE REVIEW

**Comment by aquynh** [comment]
@nl5887, can you ack?

**Comment by aquynh** [comment]
@sashs, do you have any comments on this?

**Comment by sashs** [comment]
@aquynh No, I do not. But I do not know rust. ;)

**Comment by aquynh** [comment]
Sorry wrong person :-)

**Comment by HongxuChen** [comment]
@gunyarakun @aquynh the PR looks good to me. The only thing I suggest is to update bitflags version.

**Comment by tathanhdinh** [comment]
Hello all,

Sorry for the show-off, I've done a similar work with a [new binding](https://github.com/tathanhdinh/keystone-rs). It's inspired by the original work, but not the same, e.g. `Error` type is no more a `struct` wrapper around low-level type, and it is first-class supported.

**Comment by aquynh** [comment]
@gunyarakun: i was going to merge, but this now has a conflict with other merges. can you please fix that? 

thanks

**Comment by aquynh** [comment]
@tathanhdinh, feel free to add your binding to https://github.com/keystone-engine/keystone/tree/master/bindings/README with a pull req, thanks.

**Comment by gunyarakun** [comment]
@aquynh I'll rebase the tree of this pull request and fix the conflicts.

**Comment by tathanhdinh** [comment]
@aquynh thanks a lot, but I've already added it :)
I just want to notify that I've redesigned the original work recently and this may overlap with work of @gunyarakun.

**Comment by gunyarakun** [comment]
@aquynh done.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
