### PR TITLE
Fix for issue #427

### PR DESCRIPTION
**Pull request by EdwardLarson**

### CODE REVIEW

**Comment by aquynh** [comment]
This PR changes 112 files? Please can you rebase on the latest code?

**Comment by EdwardLarson** [comment]
Fixed

**Comment by aquynh** [comment]
this fixes #427, but also includes MSP430. can you please split this fix, so it is easier to track?

**Comment by aquynh** [comment]
thanks for this amazing work, and my apologies for such a long delay!

this looks good from some quick test, but i will need to do more test on my side.
we will merge this into master for the next release after that.

thanks again!

**Pull request merged**
