### PR TITLE
fix python bindings shared library directory issue

### LINKED ISSUE #235: Python bindings - fail to load the dynamic library.
**Environment:** Kali 2.0 (sana), 64-bit.
**Version:** 0.9.1-3.
**Source:** Tried installing by cloning from github, by following instructions for keystone and bindings. Also tried from pip.

With source: looks like keystone compiles to a static library rather than a shared object. Did the lazy thing and used the pip package to install instead.

The pip package also does a cmake, with -DBUILD_SHARED_LIBS=ON. It produces the .so library here:
/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/keystone/libkeystone.so

It is not one of the paths that keystone.py searches, so keystone throws an error saying that the library was not found.

**Workaround:** One can move the file, or create a symlink in 
/usr/local/lib/python2.7/dist-packages/keystone

**Workaround 2:** One can add the following code to search in this (admittedly strange) location:
if _found == False:  
    # last try: loading from python lib directory  
    _lib_path = "/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/"
    for _lib in _all_libs:  
        try:  
            _lib_file = join(_lib_path, 'keystone', _lib)  
            #print(">> 2: Trying to load %s" %_lib_file);  
            _ks = cdll.LoadLibrary(_lib_file)  
            _found = True  
            break  
        except OSError:  
            pass

**Workaround 3:** One can install keystone with -DBUILD_SHARED_LIBS=ON and then remove the \* and (system() == 'Darwin')\* condition in keystone.py, line 62. **Note:** I tested this on Kali, not on other systems. This is probably the most elegant way of proceeding.

Please note that, after some rummaging through the source code, I tried running _setup.py install_ from the bindings/python folder, since I saw that it included compiling the library as a shared object. Not sure why (yet), but this didn't work.

### PR DESCRIPTION
**Pull request by HongxuChen**
using `data_files` dict prefixed with `SITE_PACKAGES = os.path.join(get_python_lib(), "keystone")` is not portable. Regular setup configuration does not work, e.g., specifying `package_data` etc, since that only affects `sdist`.

The fix is a hack: customize `install_lib` to explicitly copy the file into keystone install dir.

This should fix #235 and #297 .

### CODE REVIEW

**Comment by HongxuChen** [comment]
Also a bit `os.chdir(cur_dir)` to ensure after cmake build it will return to root dir even there are exceptions (merely used for local setup try).

**Comment by aquynh** [comment]
cool, did you look at the setup code of Unicorn for reference?

**Comment by HongxuChen** [comment]
@aquynh I didn't. I was just trying keystone and met the issue on my machine and didn't read your comment #297 carefully. Unicorn seems different as it also needs to include headers, etc?

**Comment by aquynh** [comment]
the difference is not big. or you can look at the setup of Capstone, which works & proven.

by porting the setup.py of Capstone or Unicorn over, we can fix other minor issues. please let me know if you can work on this, thanks.

**Comment by HongxuChen** [comment]
Okay, I will take a look at that and hopefully there is a general and consistent solution.

**Comment by HongxuChen** [comment]
Hi @aquynh , I modified both capstone and unicorn's setup files, and I think it is now consistent. It supports:

- sdist
- bdist (with wheel if possible)

`lib` and `include` are put inside the installed root directories respectively.

keystone's setup should be modified to fit for the requirement.

Please check whether you're comfortable with these changes.

[setups.zip](https://github.com/keystone-engine/keystone/files/1072058/setups.zip)

**Comment by williballenthin** [comment]
@aquynh whats the status of this PR? will it be merged soon, or are you awaiting additional fixes?

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
