### PR TITLE
+vb6 bindings

### PR DESCRIPTION
**Pull request by dzzie**

### CODE REVIEW

**Comment by aquynh** [comment]
fantastic, you are at it again!

what is the status of this binding? is there any TODO thing?

**Comment by dzzie** [comment]
everything is implemented. the symbol resolver is in place but not yet tested because at the time of writing it hadnt made it into the binary release yet and I wasnt setup to compile the dll so right now it is just commented out but there

**Comment by aquynh** [comment]
can you put your name into CREDITS.TXT & bindings/README, and also add VB6 into the list of bindings in README.md?

**Comment by dzzie** [comment]
credits updated

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
