### PR TITLE
OCaml bindings for Keystone.

### PR DESCRIPTION
**Pull request by aziem**
Hi,
I have tidied up the bindings that I had in a separate repo and merged them with the main Keystone repository. 

I have tested mainly on Linux. OS X should work fine too. I hope the README is clear enough but let me know if not and I will update. 

I have also modified the makefile in the bindings directory to allow the ocaml bindings to be built from there. 

Please do let me know if I should make any changes before this can be merged.

### CODE REVIEW

**Comment by aquynh** [comment]
excellent, thanks for doing this!

a quick question: can you make use of bindings/const_generator.py to generate all the symbols? you can look into bindings/Makefile and see that all other bindings (except Haskell, which is special) use this script to generate symbols from include/keystone/*.h, so if i add new symbols there, i just need to do:

    $ cd bindings
    $ make

then all the bindings will automatically pick up new symbols from the core. this will ease the burden of maintenance for binding authors, and keep bindings updated with the core.

**Comment by aquynh** [comment]
i am testing this on Mac. i followed all the steps in README, and got this issue at "make" step:

```
$ make
ocaml setup.ml -configure
E: Field 'findlib_version' is not set: Field 'ocamlfind' is not set
make: *** [setup.data] Error 1
```

**Comment by aziem** [comment]
Sure, I will have a go at modifying the const_generator.py script to spit out something for the OCaml bindings. 

Regarding the build error on OSX: I won't have access to a mac until next week so I can't investigate until then.

**Comment by aziem** [comment]
I can't reproduce your error on OS X. I am running on 10.10.4 and used a clean installation of homebrew and clean installation of opam. I am using OCaml version 4.02.3.

What version of OSX and OCaml are you using?

**Comment by aquynh** [comment]
my Mac is 10.11.5, and OCaml is 4.03.0.

**Comment by aziem** [comment]
I've just built with OCaml 4.03.0 and it works fine. 

Could you try removing setup.data file and building again?

**Comment by aquynh** [comment]
where is setup.data ? i dont see that file under bindings/ocaml/

**Comment by aziem** [comment]
ah - so thats not the problem! setup.data is created by the Makefile on its first run when it runs the command ocaml setup.ml -configure. Its not included in the git repo. 

Could you post the output of running:

`ocamlfind list`

**Comment by aquynh** [comment]
hmm apparently this fails

```
$ ocamlfind list
zsh: command not found: ocamlfind
```


meanwhile:

```
$ opam install ocamlfind
[NOTE] Package ocamlfind is already installed (current version is 1.6.2).
```

what is wrong?

**Comment by aziem** [comment]
I think you might need to update the environment variables by running: 

``eval `opam config env```

**Comment by aquynh** [comment]
yes, that seems to fix some issues. now `make` gives me this output:

```
...
pkg_result: .......................................... /Users/me/.opam/system/lib/result
ocamldoc: ............................................ /usr/local/bin/ocamldoc

ocaml setup.ml -build
W: Cannot find source file matching module 'Ffi_generated' in library keystone
W: Cannot find source file matching module 'Ffi_generated_types' in library keystone
W: Cannot find source file matching module 'Ffi_generated' in library keystone
W: Cannot find source file matching module 'Ffi_generated_types' in library keystone
Finished, 1 target (0 cached) in 00:00:00.
+ /Users/me/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -ccopt -I -ccopt /Users/me/.opam/system/lib/ctypes -package uchar -package result -package ctypes.stubs -package ctypes.foreign -package ctypes -o ffi_types_stubgen.cmx ffi_types_stubgen.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Cstubs, and its interface was not compiled with -opaque
+ /Users/me/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -ccopt -I -ccopt /Users/me/.opam/system/lib/ctypes -package uchar -package result -package ctypes.stubs -package ctypes.foreign -package ctypes -o ffi_generated_types.cmx ffi_generated_types.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Cstubs_internals, and its interface was not compiled with -opaque
+ /Users/me/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -ccopt -I -ccopt /Users/me/.opam/system/lib/ctypes -package uchar -package result -package ctypes.stubs -package ctypes.foreign -package ctypes -o ffi_stubgen.cmx ffi_stubgen.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Cstubs, and its interface was not compiled with -opaque
+ /Users/me/.opam/system/bin/ocamlfind ocamlc -g -I lib -package ctypes -package ctypes.stubs -ccopt -I -ccopt /Users/me/.opam/system/lib/ctypes -package uchar -package result -package ctypes.stubs -package ctypes.foreign -package ctypes -c ffi_generated_stubs.c
ffi_generated_stubs.c:47:10: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
   char* x43 = ks_strerror(x40);
         ^     ~~~~~~~~~~~~~~~~
1 warning generated.
+ /Users/me/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -ccopt -I -ccopt /Users/me/.opam/system/lib/ctypes -package uchar -package result -package ctypes.stubs -package ctypes.foreign -package ctypes -o ffi_generated.cmx ffi_generated.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Cstubs_internals, and its interface was not compiled with -opaque
Finished, 42 targets (0 cached) in 00:00:03.
$
```

it seems you can fix that warning, but it is not a big issue.

now how can i confirm everything is fine? bindings/ocaml/README does not say how, so perhaps you want to update it?

**Comment by aquynh** [comment]
do you want to update README with that command `opam config env` as well?

**Comment by aziem** [comment]
Great! I have updated the README.

To make sure everything is working fine, there is a binary to run some tests:

`./test-bindings.native`

This has been added to the README as well as the opam configuration issue. 

Regarding the warnings: I'm not sure how to get rid of them, particularly the gcc warning as that it compiling an autogenerated C file. I will investigate later.

**Comment by aquynh** [comment]
great, merged into master branch.

your name is credited in https://github.com/keystone-engine/keystone/blob/master/CREDITS.TXT & https://github.com/keystone-engine/keystone/blob/master/bindings/README

thanks for the excellent work!

**Comment by aquynh** [comment]
> Sure, I will have a go at modifying the const_generator.py script to spit out something for the OCaml bindings.

will you do this? i just made some changes in the core to add a new syntax `KS_OPT_SYNTAX_RADIX16` (see https://github.com/keystone-engine/keystone/commit/eac9cc9d6712c4417ce57cb0aedeb8f0a39667c5), then i ran:

   $ cd bindings; make

this updated all the bindings, except Ocaml (see https://github.com/keystone-engine/keystone/commit/0c56ef96ebaefdf2ec134f659ecb92daaee24452). 

so Ocaml binding is a bit behind now, with no support for `KS_OPT_SYNTAX_RADIX16`.

**Comment by aziem** [comment]
I have had a look at using the const_generator.py script but it will require me to change the structure of the bindings I think. The issue is that my bindings need to produce the ffi_types.ml file and also produce some output for the keystone.mli file. Also the const_generator script needs to generate three bits of code for my OCaml bindings: 

1. Declaring the OCaml variant type for each enum

2. Declaring some constant variables and using OCaml-Ctypes for each one to auto-generate the OCaml-C glue.

3. Using OCaml-Ctypes to gather these constants and auto-generate enum code to associate the variant type with the equivelant enum in the header file.

I can't see a clean way of doing it without making big modifications to the script and/or modifying the structure of the OCaml bindings. 

I actually have a prototype purely OCaml implementation of autogenerating the constants for the bindings but I still need to test it more. Essentially I parse  keystone.h file (preprocessed by gcc or clang depending on platform) and for the enums/constants I autogenerate the OCamlhcode necessary for constant bindings and then carry on building the OCaml bindings as is done at the moment.  I haven't tested it on non-OSX *BSD, and I suspect Windows might be a problem too as I don't know which C compiler I will have access to there. 

For now I can update the bindings by hand and send a pull request which I will try and do later today or tomorrow.

**Comment by aquynh** [comment]
I see. Then please send a pull req to update that manually, thanks.

**Pull request merged**
