### PR TITLE
Introduction of the Java bindings

### PR DESCRIPTION
**Pull request by ZenLulz**
Dear Keystone developers and supporters,

First at all, many thanks for this amazing library! As part of my Bachelor's thesis, I needed a tool to assemble assembly code on a JVM language. For that purpose, I have written a Java binding for Keystone, fully documented and unit tested (98%). All the required instructions to get started are enclosed in the README.md, located in the *bindings/java* folder.

Don't hesitate to post your questions, feedbacks or other forms of observation. Code reviews are a great mechanism to produce quality code! I have tested the bindings on Windows and macOS.

-----
Side note: It seems Keystone 0.9.1 does not embed the option to resolve unrecognised symbols. Indeed, 0.9.1 has been released on July 2016 and the introduction of the symbol resolver callback has been introduced in October 2016, according a *git blame* on *keystone.h*. Therefore, if you do not compile Keystone on your own, some unit tests of the Java bindings will fail. I would recommend releasing Keystone 0.9.2 to package the latest features available since 2016. 😃

Best Regards,
ZenLulz

### CODE REVIEW

**Comment by aquynh** [comment]
awesome, thanks for this great work!

what do you want to keep in bindings/java/src/main/resources/ directory?

**Comment by ZenLulz** [comment]
Hello !

Many thanks! The `resources` folder contains the binaries of Keystone, compiled for the system(s) the developer would like to target. As an example, let's suppose I would like to build a cross-platform application using Keystone (Windows and macOS). I would need to compile (or download) Keystone for Windows and macOS and store the compiled files into the `resources` folder. Afterwards, JNA, the underlying technology invoking the native functions, is able to pick the right library, depending on the operating system where the application runs.

Don't hesitate if you have other questions or feedback !

**Comment by aquynh** [comment]
why do we need to keep that directory, even it is empty?

**Comment by ZenLulz** [comment]
This is mostly to guide people who are not familiar with JNA. Do you think we should remove it ?

**Comment by aquynh** [comment]
that is OK to keep it there.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by ZenLulz** [comment]
Thank you !

**Pull request merged**
