### PR TITLE
Add round-trip test cases

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
basically most (or all - i still need to double-check) of these issues are due to Capstone is not synced with the version of LLVM which Keystone is based on (more recent). once we update Capstone to the same LLVM version, the problem will be solved. thanks.

**Comment by practicalswift** [comment]
@aquynh I see! Do you still want new round-trip test cases added or should I stop submitting them? :-)

**Comment by aquynh** [comment]
oh why not, this is very useful so we are aware of all the buggy instructions & can confirm later that all the problems are fixed. 

so please keep sending PRs on this issue, thanks!

**Pull request merged**
