### PR TITLE
Adding unit test for arm_bl relative branch

### PR DESCRIPTION
**Pull request by shakamd**
https://github.com/keystone-engine/keystone/issues/257

### CODE REVIEW

**Comment by aquynh** [comment]
Can you keep only 2 instructions (one + the BL) to keep it simple and easier to debug?

**Comment by shakamd** [comment]
Sure, I've reduced it to the minimum number of required instructions to reproduce the failure.

**Comment by aquynh** [comment]
you can even use NOP instructions before the BL to make it more simple.

if the bug does not happen with 1 instruction before BL, can you also add that case, too? (it is OK to have more than 1 test in a same file)

**Comment by shakamd** [comment]
Ok, there are 3 separate test cases now (the last one fails).

**Comment by aquynh** [comment]
interesting, so the 2nd case also has 3 instructions, but it does not fail?

merged, thanks!

**Comment by shakamd** [comment]
That's correct! Puzzling indeed.

**Pull request merged**
